In [1]:
import numpy as np

In [2]:
testA = np.array([5, 6, 7, np.nan, 8, 1, 2, 4, np.nan, 3, 1, 9])

In [3]:
def sub2ind(array_shape, rows, cols):
    ind = rows*array_shape[1] + cols
    ind[ind < 0] = -1
    ind[ind >= array_shape[0]*array_shape[1]] = -1
    return ind

In [4]:
def nanmedfilt(A, sz=5):
    """ Median filtering of 1D or 2D array, A, while ignoring NaNs using tile size of sz
    adapted from https://www.mathworks.com/matlabcentral/fileexchange/41457-nanmedfilt2
    """
    if type(sz)==int:
        sz = np.array([sz,sz])
    if any(sz%2 == 0):
        print('kernel size must be odd')
    margin = np.array((sz-1)//2)
    if len(np.shape(A))==1:
        A = np.expand_dims(A, axis=0)
    AA = np.zeros(np.squeeze(np.array(np.shape(A))+2*np.expand_dims(margin,0)))
    AA[:] = np.nan
    AA[margin[0]:-margin[0], margin[1]:-margin[1]] = A
    iB, jB = np.mgrid[0:sz[0],0:sz[1]]
    isB = sub2ind(np.shape(AA.T),jB,iB)+1
    iA, jA = np.mgrid[0:np.size(A,0),0:np.size(A,1)]
    iA += 1
    isA = sub2ind(np.shape(AA.T),jA,iA)
    idx = isA + np.expand_dims(isB.flatten('F')-1,1)
    
    B = np.sort(AA.T.flatten()[idx-1],0)
    j = np.any(np.isnan(B),0)
    last = np.zeros([1,np.size(B,1)])+np.size(B,0)
    last[:,j] = np.argmax(np.isnan(B[:,j]),0)
    
    M = np.zeros([1,np.size(B,1)])
    M[:] = np.nan
    valid = np.where(last>0)[1]
    mid = (1+last)/2
    i1 = np.floor(mid[:,valid])
    i2 = np.ceil(mid[:,valid])
    i1 = sub2ind(np.shape(B.T),valid,i1)
    i2 = sub2ind(np.shape(B.T),valid,i2)
    M[:,valid] = 0.5*(B.flatten('F')[i1.astype(int)-1] + B.flatten('F')[i2.astype(int)-1])
    M = np.reshape(M, np.shape(A))
    
    return M

In [5]:
testA

array([ 5.,  6.,  7., nan,  8.,  1.,  2.,  4., nan,  3.,  1.,  9.])

In [6]:
M = nanmedfilt(testA, 5)
M

array([[6. , 6. , 6.5, 6.5, 4.5, 3. , 3. , 2.5, 2.5, 3.5, 3. , 3. ]])

In [351]:
i1 = np.floor(mid[:,valid])
i2 = np.ceil(mid[:,valid])
i1 = sub2ind(np.shape(B.T),valid,i1)
i2 = sub2ind(np.shape(B.T),valid,i2)

In [325]:
np.shape(M)

(1, 12)

In [334]:
np.shape(B)

(25, 12)

In [352]:
i1

array([[  2.,  27.,  52.,  77., 102., 127., 152., 177., 202., 227., 252.,
        277.]])

In [354]:
np.shape(i1)

(1, 12)

In [355]:
np.shape(B)

(25, 12)

In [371]:
M[:,valid] = 0.5*(B.flatten('F')[i1.astype(int)-1] + B.flatten('F')[i2.astype(int)-1])

In [372]:
M

array([[6. , 6. , 6.5, 6.5, 4.5, 3. , 3. , 2.5, 2.5, 3.5, 3. , 3. ]])

In [317]:
i1 = sub2ind(np.shape(B.T),valid,i1)
i1_new

array([[  2.,  27.,  52.,  77., 102., 127., 152., 177., 202., 227., 252.,
        277.]])

In [ ]:
i2 = sub2ind(np.size(B),i2,valid)

In [313]:
i1 = np.floor(mid[:,valid])
i2 = np.ceil(mid[:,valid])
print(i1, i2)

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]] [[2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 2. 2.]]


In [311]:
mid = (1+last)/2
mid

array([[2. , 2. , 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2. , 2. ]])

In [303]:
M = np.zeros([1, np.size(B,1)])
M[:] = np.nan
M

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [310]:
valid = np.where(last>0)[1]

In [297]:
j = np.any(np.isnan(B),0)
last = np.zeros([1,np.size(B,1)])+np.size(B,0)
last[:,j] = np.argmax(np.isnan(B[:,j]),0)

In [298]:
last

array([[3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 3., 3.]])

In [285]:
[~, last(j)]=max(isnan(B(:,j)),[],1)

SyntaxError: invalid syntax (3918940292.py, line 1)

In [267]:
idx = isA + np.expand_dims(isB.flatten('F')-1,1)

In [249]:
isA.flatten()

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56])

In [247]:
isB.flatten('F')-1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
       [ 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61],
       [ 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62],
       [ 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63],
       [ 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64],
       [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65],
       [11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66],
       [12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67],
       [13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68],
       [14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69],
       [15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
       [16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71],
       [17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72],
       [18, 23, 28, 33, 38, 43,

In [211]:
iA, jA = np.mgrid[0:np.size(A,0),0:np.size(A,1)]

In [212]:
iA

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [213]:
jA

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [144]:
is=sub2ind(size(AA),iB,jB);

(5, 16)

In [142]:
AA[2:-2]

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan]])

In [148]:
AA[margin[0]:-margin[0], margin[1]:-margin[1]] = A

In [152]:
iB, jB = np.mgrid[0:sz[0],0:sz[1]]

In [154]:
jB

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [96]:
np.array(np.shape(A))+2

array([ 3, 14])

In [77]:
B = np.expand_dims(testA, axis=0)

In [78]:
np.shape(B)

(1, 12)

In [79]:
margin = np.array([2,2])
np.shape(B)+2*margin

array([ 5, 16])

In [ ]:
np.shape(tse)

[2 2]


TypeError: only integer scalar arrays can be converted to a scalar index

In [55]:
np.array(np.shape(testA))+2*np.array([2,2])

array([16, 16])

In [ ]:
AA = nan(size(A)+2*margin);
AA(1+margin(1):end-margin(1),1+margin(2):end-margin(2))=A;
[iB,jB]=ndgrid(1:sz(1),1:sz(2));
is=sub2ind(size(AA),iB,jB);
[iA, jA]=ndgrid(1:size(A,1),1:size(A,2));
iA=sub2ind(size(AA),iA,jA);
idx=bsxfun(@plus,iA(:).',is(:)-1);